### ISSUE TITLE
为什么每次get之前，都有一个option请求

### ISSUE THREAD

**Issue by kong6001** [Jamling/uni-request#1]
为什么每次get之前，都有一个option请求

**Comment by Jamling** [comment]
哈哈，你这问题超出了我的认知范围，我自己也是一知半解的，不敢误人子弟，我建议你google一下。虽然我不能回答你，但我可以负责任的告诉你，所有的浏览器也会自动加Option请求的。

**Comment by kong6001** [comment]
> 哈哈，你这问题超出了我的认知范围，我自己也是一知半解的，不敢误人子弟，我建议你google一下。虽然我不能回答你，但我可以负责任的告诉你，所有的浏览器也会自动加Option请求的。

已经科普过了，是为了AJAX跨域请求时候提高效率。json类型都会加，有几种类型的请求是不会加option的例如表单类型的请求
