### ISSUE TITLE
如何在 `interceptor.request` 时动态修改 `baseUrl`?

### ISSUE THREAD

**Issue by d1y** [Jamling/uni-request#4]
踩了很多坑, 大佬可以提个思路吗

```js
// 错误的❎..
axios.interceptor.request = (req: any)=> {
  const baseUrl = getMirror()
  axios.setConfig({
    baseUrl
  })
  return req
}
```

**Comment by Jamling** [comment]
大哥，你这不是uni-request，建议去axios项目咨询。

我这里有个思路（仅适用于H5环境），供参考一下：

1. mafinest.json中添加多个代理，不同的代理指向不同的接口基地址
2. 请求的url中使用不同的代理路径

**Comment by d1y** [comment]
> 大哥，你这不是uni-request，建议去axios项目咨询。
> 
> 我这里有个思路（仅适用于H5环境），供参考一下：
> 
> 1. mafinest.json中添加多个代理，不同的代理指向不同的接口基地址
> 2. 请求的url中使用不同的代理路径

我只是自己改了变量名而已, 实际上还是用的这个插件..

参见: 

https://github.com/waifu-project/18comic/blob/54bf872acf1107df24b11d464fbea5ff008fa40b/src/utils/axios.ts#L26

**Comment by Jamling** [comment]
我打开链接看过了，你用的是axios。
虽然请求框架包括api都相似，但是工作原理未必一致。

uni-request，只设计了一个baseUrl，其它的绝对url不会拼接baseUrl，所以：
1，如果是个别url请求不一样，建议使用绝对url
2，如果是有许多url请求不一样，建议使用空的baseUrl，然后通过我上面的思路（动态代理）来实现。
