### ISSUE TITLE
在最新的HbuildX版本 2020年07月28日的插件报错了

### ISSUE THREAD

**Issue by LancCJ** [Jamling/uni-request#5]
如题所示，请求目前都是404了，HbuildX 从 2020年07月26日 版本开始，基座调试可以的一打包后的APK使用就存在问题，希望排查下

**Comment by LancCJ** [comment]
06:19:55.446 request: , [Object] {"url":"http://www.tianqiapi.com/api?version=v9&appid=23035354&appsecret=8YvlPNrz","business":"data","meth...}  at common/j-request/request.js:312
06:19:55.488 response failure: , [Object] {"data":{"cityid":"101190401","city":"苏州","cityEn":"suzhou","country":"中国","countryEn":"China","update_tim...}  at common/j-request/request.js:279
06:19:55.508 failure at pages/index/index.vue:48
06:19:55.533 request completed in 60 ms at common/j-request/request.js:323
06:19:55.559 complete, [Object] {"data":{"cityid":"101190401","city":"苏州","cityEn":"suzhou","country":"中国","countryEn":"China","update_tim...}  at pages/index/index.vue:53
06:20:37.135 开始差量编译...
06:20:37.435  DONE  Build complete. FILES:["app-service.js"]
06:20:37.435 项目 'j-request示例' 编译成功。
06:20:37.455 正在同步手机端程序文件...
06:20:37.475 /Users/chenjian/Documents/code/j-request/j-request示例/unpackage/dist/dev/app-plus/app-service.js: 1 file pushed. 27.9 MB/s (323329 bytes in 0.011s)
06:20:37.499 同步手机端程序文件完成
06:20:37.525 正在热刷新，如刷新失败，请点击控制台工具栏上的【重启应用图标】
06:20:37.797 [Object] {"config":{"baseUrl":"","business":"data"},"interceptor":{}}  at main.js:4
06:20:37.822 App Launch at App.vue:4
06:20:37.843 App Show at App.vue:7
06:20:39.781 request: , [Object] {"url":"http://www.tianqiapi.com/api?version=v9&appid=23035354&appsecret=8YvlPNrz","business":"data","meth...}  at common/j-request/request.js:312
06:20:39.830 response failure: , [Object] {"data":{"cityid":"101190401","city":"苏州","cityEn":"suzhou","country":"中国","countryEn":"China","update_tim...}  at common/j-request/request.js:279
06:20:39.855 failure at pages/index/index.vue:48
06:20:39.878 request completed in 60 ms at common/j-request/request.js:323
06:20:39.900 complete, [Object] {"data":{"cityid":"101190401","city":"苏州","cityEn":"suzhou","country":"中国","countryEn":"China","update_tim...}  at pages/index/index.vue:53

**Comment by LancCJ** [comment]
测试URL     http://www.tianqiapi.com/api?version=v9&appid=23035354&appsecret=8YvlPNrz

现象   请求完毕后中间有个小遮罩   测试方式是 将 插件示例代码下载下来修改 baseUrl 然后界面的 url为 “”，其他都没动  HbuildX版本为最新  2.8.3.20200728 的版本 ，就这几天这样的，低版本HbuildX打包还没这个问题
![Screenshot_20200730_062446_io dcloud HBuilder](https://user-images.githubusercontent.com/2968042/88860000-76fee900-d22d-11ea-84f0-5a43e8eb54b7.jpg)

**Comment by LancCJ** [comment]
@Jamling Jamling

**Comment by Jamling** [comment]
这应该是baseUrl为空导致的。你改为非空url试试

**Comment by Jamling** [comment]
示例api（万年历）都404, 是因为服务器没有续费

**Comment by LancCJ** [comment]
> 这应该是baseUrl为空导致的。你改为非空url试试

我检查了下不是为空，我开启debug看了下请求JSON串，我觉得Url的问题
`{ "url": "http://yuming.com:8080/appname/api/login", "loadingTip": "用户登录中...", "data": { "mobile": "", "password": "", "uid": 100 }, "method": "POST", "header": { "Content-Type": "application/json;charset=UTF-8", "token": "my_token" }, "baseUrl": "http://yuming.com:8080/appname", "debug": true, "toastError": true }`

上面 yuming.com 域名是我替换了正式的 appname也是替换正式的 ，请理解不把正式的暴露出来，我想表达的意思是Url那边我觉得拼接错了，但是这种情况只有我在   使用自定义基座的时候发生

**Comment by LancCJ** [comment]
> > 这应该是baseUrl为空导致的。你改为非空url试试
> 
> 我检查了下不是为空，我开启debug看了下请求JSON串，我觉得Url的问题
> `{ "url": "http://yuming.com:8080/appname/api/login", "loadingTip": "用户登录中...", "data": { "mobile": "", "password": "", "uid": 100 }, "method": "POST", "header": { "Content-Type": "application/json;charset=UTF-8", "token": "my_token" }, "baseUrl": "http://yuming.com:8080/appname", "debug": true, "toastError": true }`
> 
> 上面 yuming.com 域名是我替换了正式的 appname也是替换正式的 ，请理解不把正式的暴露出来，我想表达的意思是Url那边我觉得拼接错了，但是这种情况只有我在 使用自定义基座的时候发生

刚我把参数slashAbsoluteUrl改为true后json格式如下
`{ "url": "/api/login", "loadingTip": "用户登录中...", "data": { "mobile": "", "password": "", "uid": 100 }, "method": "POST", "header": { "Content-Type": "application/json;charset=UTF-8", "token": "my_token" }, "baseUrl": "http://yuming.com:8080/appname", "debug": true, "toastError": true }`

但是效果还是报错  request:fail abort statusCode:-1  哎 这是为啥呢。。。

**Comment by LancCJ** [comment]
> > > 这应该是baseUrl为空导致的。你改为非空url试试
> > 
> > 
> > 我检查了下不是为空，我开启debug看了下请求JSON串，我觉得Url的问题
> > `{ "url": "http://yuming.com:8080/appname/api/login", "loadingTip": "用户登录中...", "data": { "mobile": "", "password": "", "uid": 100 }, "method": "POST", "header": { "Content-Type": "application/json;charset=UTF-8", "token": "my_token" }, "baseUrl": "http://yuming.com:8080/appname", "debug": true, "toastError": true }`
> > 上面 yuming.com 域名是我替换了正式的 appname也是替换正式的 ，请理解不把正式的暴露出来，我想表达的意思是Url那边我觉得拼接错了，但是这种情况只有我在 使用自定义基座的时候发生
> 
> 刚我把参数slashAbsoluteUrl改为true后json格式如下
> `{ "url": "/api/login", "loadingTip": "用户登录中...", "data": { "mobile": "", "password": "", "uid": 100 }, "method": "POST", "header": { "Content-Type": "application/json;charset=UTF-8", "token": "my_token" }, "baseUrl": "http://yuming.com:8080/appname", "debug": true, "toastError": true }`
> 
> 但是效果还是报错 request:fail abort statusCode:-1 哎 这是为啥呢。。。

改成true应该是错误的，会导致 标准运行基座下也出现相同问题。。。。还是改回去默认flase

**Comment by LancCJ** [comment]
> > > > 这应该是baseUrl为空导致的。你改为非空url试试
> > > 
> > > 
> > > 我检查了下不是为空，我开启debug看了下请求JSON串，我觉得Url的问题
> > > `{ "url": "http://yuming.com:8080/appname/api/login", "loadingTip": "用户登录中...", "data": { "mobile": "", "password": "", "uid": 100 }, "method": "POST", "header": { "Content-Type": "application/json;charset=UTF-8", "token": "my_token" }, "baseUrl": "http://yuming.com:8080/appname", "debug": true, "toastError": true }`
> > > 上面 yuming.com 域名是我替换了正式的 appname也是替换正式的 ，请理解不把正式的暴露出来，我想表达的意思是Url那边我觉得拼接错了，但是这种情况只有我在 使用自定义基座的时候发生
> > 
> > 
> > 刚我把参数slashAbsoluteUrl改为true后json格式如下
> > `{ "url": "/api/login", "loadingTip": "用户登录中...", "data": { "mobile": "", "password": "", "uid": 100 }, "method": "POST", "header": { "Content-Type": "application/json;charset=UTF-8", "token": "my_token" }, "baseUrl": "http://yuming.com:8080/appname", "debug": true, "toastError": true }`
> > 但是效果还是报错 request:fail abort statusCode:-1 哎 这是为啥呢。。。
> 
> 改成true应该是错误的，会导致 标准运行基座下也出现相同问题。。。。还是改回去默认flase

和你插件应该没问题，应该是 我自定义基座的问题，不好意思了
